/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type RelationshipType =
  "association" | "aggregation" | "composition" | "inheritance" | "dependency" | "realization";
export type RequirementType = "functional" | "nonFunctional";

/**
 * A confirmed CPM. Referentially complete, safe to render from.
 */
export interface CPM {
  actors?: Actor[];
  components?: Component[];
  entities?: Entity[];
  flows?: Flow[];
  meta: Meta;
  nodes?: Node[];
  relationships?: Relationship[];
  requirements?: Requirement[];
  states?: State[];
  useCases?: UseCase[];
}
export interface Actor {
  description?: string;
  id: string;
  isPrimary?: boolean;
  name: string;
}
export interface Component {
  id: string;
  name: string;
  provides?: string[];
  requires?: string[];
  type: string;
}
export interface Entity {
  attributes?: Attribute[];
  description?: string;
  id: string;
  methods?: Method[];
  name: string;
}
export interface Attribute {
  isKey?: boolean;
  isRequired?: boolean;
  name: string;
  type: string;
}
export interface Method {
  name: string;
  params?: string[];
  returns: string;
}
export interface Flow {
  id: string;
  name: string;
  participants?: string[];
  steps?: FlowStep[];
}
export interface FlowStep {
  from: string;
  message: string;
  order: number;
  to: string;
}
export interface Meta {
  authors?: string[];
  createdAt: string;
  description?: string;
  projectName: string;
  version?: string;
}
export interface Node {
  deployedComponents?: string[];
  id: string;
  name: string;
  type: string;
}
export interface Relationship {
  cardinality?: string | null;
  from: string;
  id: string;
  label?: string | null;
  to: string;
  type: RelationshipType;
}
export interface Requirement {
  id: string;
  priority: string;
  text: string;
  type: RequirementType;
}
export interface State {
  entityRef: string;
  id: string;
  isFinal?: boolean;
  isInitial?: boolean;
  name: string;
  transitions?: Transition[];
}
export interface Transition {
  guard?: string | null;
  to: string;
  trigger?: string | null;
}
export interface UseCase {
  actors?: string[];
  alternateFlows?: string[];
  id: string;
  mainFlow?: string[];
  name: string;
  postconditions?: string[];
  preconditions?: string[];
}
