"""The Canonical Project Model.

THE architectural rule: every diagram and every document section is rendered
from this model. Nothing downstream may call the LLM again, because that is
what would let two artefacts disagree about the same entity.

Two model classes, deliberately:

* :class:`CPMDraft` — structurally valid. Types, id formats and enums are
  enforced, but references may dangle. This is what the review gate holds
  while the user is still fixing things.
* :class:`CPM` — a draft that additionally passes every referential integrity
  check. Nothing may be rendered from anything less.

Python fields are snake_case; the wire format is camelCase, generated by an
alias generator so the two can never disagree by hand.
"""

from datetime import datetime
from enum import StrEnum
from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field, StringConstraints, model_validator
from pydantic.alias_generators import to_camel

from cpm.ids import Slug

Name = Annotated[str, StringConstraints(strip_whitespace=True, min_length=1, max_length=200)]
Sentence = Annotated[str, StringConstraints(strip_whitespace=True, min_length=1, max_length=2000)]
Description = Annotated[str, StringConstraints(strip_whitespace=True, max_length=4000)]


class CPMBase(BaseModel):
    """Shared config for every CPM node.

    ``extra="forbid"`` is the important one. The CPM is populated by an LLM; an
    unexpected key means the extractor and this schema disagree, and that is a
    signal worth failing on rather than silently discarding.
    """

    model_config = ConfigDict(
        alias_generator=to_camel,
        populate_by_name=True,
        extra="forbid",
    )


class RelationshipType(StrEnum):
    ASSOCIATION = "association"
    AGGREGATION = "aggregation"
    COMPOSITION = "composition"
    INHERITANCE = "inheritance"
    DEPENDENCY = "dependency"
    REALIZATION = "realization"


class RequirementType(StrEnum):
    FUNCTIONAL = "functional"
    NON_FUNCTIONAL = "nonFunctional"


class Meta(CPMBase):
    project_name: Name
    description: Description = ""
    authors: list[Name] = Field(default_factory=list)
    version: Name = "1.0"
    created_at: datetime


class Actor(CPMBase):
    id: Slug
    name: Name
    description: Description = ""
    is_primary: bool = False


class Attribute(CPMBase):
    name: Name
    type: Name
    is_key: bool = False
    is_required: bool = False


class Method(CPMBase):
    name: Name
    returns: Name
    params: list[Name] = Field(default_factory=list)


class Entity(CPMBase):
    id: Slug
    name: Name
    description: Description = ""
    attributes: list[Attribute] = Field(default_factory=list)
    methods: list[Method] = Field(default_factory=list)


class Relationship(CPMBase):
    id: Slug
    # "from" is a Python keyword. The field is from_ here and "from" on the
    # wire; a renderer reading "from_" would silently find nothing.
    from_: Slug = Field(alias="from")
    to: Slug
    type: RelationshipType
    cardinality: Name | None = None
    label: Name | None = None


class UseCase(CPMBase):
    id: Slug
    name: Name
    actors: list[Slug] = Field(default_factory=list)
    preconditions: list[Sentence] = Field(default_factory=list)
    main_flow: list[Sentence] = Field(default_factory=list)
    alternate_flows: list[Sentence] = Field(default_factory=list)
    postconditions: list[Sentence] = Field(default_factory=list)


class FlowStep(CPMBase):
    from_: Slug = Field(alias="from")
    to: Slug
    message: Name
    order: int = Field(ge=1)


class Flow(CPMBase):
    id: Slug
    name: Name
    participants: list[Slug] = Field(default_factory=list)
    steps: list[FlowStep] = Field(default_factory=list)


class Transition(CPMBase):
    to: Slug
    trigger: Name | None = None
    guard: Name | None = None


class State(CPMBase):
    id: Slug
    entity_ref: Slug
    name: Name
    is_initial: bool = False
    is_final: bool = False
    transitions: list[Transition] = Field(default_factory=list)


class Component(CPMBase):
    id: Slug
    name: Name
    type: Name
    # Interface names, not id references — a component may provide an interface
    # no other component in the model consumes.
    provides: list[Name] = Field(default_factory=list)
    requires: list[Name] = Field(default_factory=list)


class Node(CPMBase):
    id: Slug
    name: Name
    type: Name
    deployed_components: list[Slug] = Field(default_factory=list)


class Requirement(CPMBase):
    id: Slug
    type: RequirementType
    text: Sentence
    priority: Name


class CPMCollections(CPMBase):
    """Everything the model contains, without the project metadata.

    Split out so extraction can ask an LLM for exactly this and no more. Meta
    carries a project name and a creation timestamp, neither of which the model
    should be inventing — and a schema that asks for a timestamp is inviting
    precisely the fabrication the extraction floor exists to prevent.
    """

    actors: list[Actor] = Field(default_factory=list)
    entities: list[Entity] = Field(default_factory=list)
    relationships: list[Relationship] = Field(default_factory=list)
    use_cases: list[UseCase] = Field(default_factory=list)
    flows: list[Flow] = Field(default_factory=list)
    states: list[State] = Field(default_factory=list)
    components: list[Component] = Field(default_factory=list)
    nodes: list[Node] = Field(default_factory=list)
    requirements: list[Requirement] = Field(default_factory=list)


class CPMDraft(CPMCollections):
    """A structurally valid CPM whose references may still dangle."""

    meta: Meta


class CPM(CPMDraft):
    """A confirmed CPM. Referentially complete, safe to render from."""

    @model_validator(mode="after")
    def _enforce_referential_integrity(self) -> "CPM":
        # Imported here rather than at module scope: cpm.integrity needs
        # CPMDraft from this module, and a top-level import would be circular.
        from cpm.integrity import check_integrity

        issues = check_integrity(self)
        if issues:
            detail = "\n".join(
                f"  [{issue.code.value}] {issue.path}: {issue.message}" for issue in issues
            )
            raise ValueError(f"CPM failed referential integrity:\n{detail}")
        return self
